import Navbar from "./components/Navbar/Navbar";
import "./globals.css";
import { Kumbh_Sans } from "next/font/google";

const font = Kumbh_Sans({
    subsets: ["latin"],
});
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={font.className}>
                <Navbar />
                <div>{children}</div>
            </body>
        </html>
    );
}
